{% set version = "12.8.1" %}

package:
  name: cuda-visual-tools
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 1
  skip: true  # [osx or ppc64le]

requirements:
  run:
    - cuda-nsight 12.8.90               # [linux64]
    - nsight-compute 2025.1.1.2
    - cuda-nvml-dev 12.8.90
    - cuda-nvvp 12.8.93                 # [not aarch64]
    - cuda-libraries-dev {{ version }}

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Contains the visual tools to debug and profile CUDA applications
  description: |
    Contains the visual tools to debug and profile CUDA applications
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
